### ISSUE TITLE
用語見直し

### ISSUE THREAD

**Issue by tyokinuhata** [uyupun/menstagram-web#130]

**Comment by takashi0602** [comment]
ドキュメントの[用語集](https://github.com/uyupun/menstagram-docs/blob/master/terms.md)にて対応済みで、カンプも修正したため閉じます

**Comment by tyokinuhata** [comment]
これはフロントエンドの用語を全て修正するというタスクなので完了してないです

**Comment by tyokinuhata** [comment]
別issues立っていたので閉じます
https://github.com/uyupun/menstagram-web/issues/144
